### ISSUE TITLE
consider adding this to contrib section of exhibitor wiki 

### ISSUE THREAD

**Issue by aisch** [playlist-ansible/zookeeper#10]
see https://github.com/Netflix/exhibitor/wiki/Contributions

afaik this is the only ansible role that gives u an auto-scaling zk ensemble in aws w/ a few lines of yaml. only gripe was not finding it sooner.

**Comment by jacobwgillespie** [comment]
Added an issue at Netflix/exhibitor#288 (as the wiki is locked to contributors only).  Closing this issue.
