### ISSUE TITLE
cut a release

### ISSUE THREAD

**Issue by aisch** [playlist-ansible/zookeeper#6]
would it be possible to create a release for this role (e.g. `v0.1.0`)? currently just pinning to a commit hash.

**Comment by jacobwgillespie** [comment]
Yep - tagged as `v1.0.0` (gotta start somewhere!)

**Comment by aisch** [comment]
:beers: hopefully that gets reflected @ https://galaxy.ansible.com/detail#/role/3317 which seems pretty stale
